name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest


  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate website
        run: python app.py

      - name: Check website
        run: test -f site/index.html

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: deployed-website
          path: site